[package]
name = "aksh-conformance"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
aksh-gha-parser = { path = "../aksh-gha-parser" }
aksh-gha-protocol = { path = "../aksh-gha-protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
walkdir.workspace = true
flate2.workspace = true
tar.workspace = true
serde_yaml.workspace = true


runner-watch = { path = "../runner-watch" }
tempfile.workspace = true
reqwest.workspace = true
