//! Generates version-pin constants from `versions.toml` at the workspace
//! root, so every pinned version lives in one version-controlled file
//! instead of as literals scattered through the code.
//!
//! The file is deliberately flat (`key = "value"` lines, `#` comments) so
//! this parser stays trivial and any tooling (Renovate regex managers, etc.)
//! can bump keys without understanding TOML structure.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let versions_path = manifest_dir.join("../../versions.toml");
    let text = fs::read_to_string(&versions_path).expect("versions.toml must exist");

    let mut out = String::from("// Generated by build.rs from versions.toml. Do not edit.\n");
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let value = value.trim();
        if !(value.starts_with('"') && value.ends_with('"')) {
            continue;
        }
        let value = &value[1..value.len() - 1];
        let const_name = key.trim().to_uppercase();
        out.push_str(&format!("pub const {const_name}: &str = \"{value}\";\n"));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("pins.rs"), out).expect("write pins.rs");
    println!("cargo:rerun-if-changed=../../versions.toml");
}
