//! Generates the SmolVM version pin for the updater from `versions.toml` at
//! the workspace root, so the runtime floor lives in the same
//! version-controlled file as every other pin instead of as a literal in the
//! updater.
//!
//! The file is deliberately flat (`key = "value"` lines, `#` comments) so
//! this parser stays trivial and any tooling (Renovate regex managers, etc.)
//! can bump keys without understanding TOML structure. Only keys this crate
//! consumes are emitted, keeping generated consts warning-free.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let versions_path = manifest_dir.join("../../versions.toml");
    let text = fs::read_to_string(&versions_path).expect("versions.toml must exist");

    const WANTED: [&str; 1] = ["smolvm_min_version"];
    let mut out = String::from("// Generated by build.rs from versions.toml. Do not edit.\n");
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if !WANTED.contains(&key) {
            continue;
        }
        let value = value.trim();
        if !(value.starts_with('"') && value.ends_with('"')) {
            continue;
        }
        let value = &value[1..value.len() - 1];
        let const_name = key.to_uppercase();
        out.push_str(&format!("pub const {const_name}: &str = \"{value}\";\n"));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("pins.rs"), out).expect("write pins.rs");
    println!("cargo:rerun-if-changed=../../versions.toml");

    // Embed the exact source commit this binary was built from. The updater
    // uses it to resolve same-version installs: a source build from newer
    // main reports the same version string as the latest release tag, and
    // byte-comparing the binaries would clobber the newer build with the
    // stale release asset. The commit is the monotonic signal the version
    // string cannot carry. Release assets are built in CI from a git
    // checkout, so the SHA is always present there; a non-git build (e.g.
    // `cargo install` from a crates.io tarball) falls back to a sentinel
    // that the updater treats as "cannot verify, keep what is installed".
    let commit = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|sha| sha.trim().to_owned())
        .filter(|sha| !sha.is_empty())
        .unwrap_or_else(|| "unknown".to_owned());
    println!("cargo:rustc-env=PRELOOP_BUILD_COMMIT={commit}");
    println!("cargo:rerun-if-changed=../../.git/HEAD");
}
