//! Generates the SmolVM version pin for the updater from `versions.toml` at
//! the workspace root, so the runtime floor lives in the same
//! version-controlled file as every other pin instead of as a literal in the
//! updater.
//!
//! The file is deliberately flat (`key = "value"` lines, `#` comments) so
//! this parser stays trivial and any tooling (Renovate regex managers, etc.)
//! can bump keys without understanding TOML structure. Only keys this crate
//! consumes are emitted, keeping generated consts warning-free.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let versions_path = manifest_dir.join("../../versions.toml");
    let text = fs::read_to_string(&versions_path).expect("versions.toml must exist");

    let mut pins: BTreeMap<String, String> = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().to_owned();
        let value = value.trim();
        if !(value.starts_with('"') && value.ends_with('"')) {
            continue;
        }
        let value = value[1..value.len() - 1].to_owned();
        pins.insert(key, value);
    }

    let mut out = String::from("// Generated by build.rs from versions.toml. Do not edit.\n");
    // Emit requested keys if present.
    const WANTED: [&str; 3] = [
        "smolvm_min_version",
        "node20_externals_version",
        "node24_externals_version",
    ];
    for key in WANTED {
        if let Some(value) = pins.get(key) {
            let const_name = key.to_uppercase();
            out.push_str(&format!("pub const {const_name}: &str = \"{value}\";\n"));
        }
    }
    // Fallback for node versions if absent (keep compilation against older TOML).
    if !pins.contains_key("node20_externals_version") && !pins.contains_key("node20_version") {
        out.push_str("pub const NODE20_EXTERNALS_VERSION: &str = \"20.19.0\";\n");
    } else if pins.contains_key("node20_version") && !pins.contains_key("node20_externals_version")
    {
        let v = pins.get("node20_version").unwrap();
        out.push_str(&format!(
            "pub const NODE20_EXTERNALS_VERSION: &str = \"{v}\";\n"
        ));
    }
    if !pins.contains_key("node24_externals_version") && !pins.contains_key("node24_version") {
        out.push_str("pub const NODE24_EXTERNALS_VERSION: &str = \"24.3.0\";\n");
    } else if pins.contains_key("node24_version") && !pins.contains_key("node24_externals_version")
    {
        let v = pins.get("node24_version").unwrap();
        out.push_str(&format!(
            "pub const NODE24_EXTERNALS_VERSION: &str = \"{v}\";\n"
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("pins.rs"), out).expect("write pins.rs");
    println!("cargo:rerun-if-changed=../../versions.toml");

    // Embed the exact source commit this binary was built from. The updater
    // uses it to resolve same-version installs: a source build from newer
    // main reports the same version string as the latest release tag, and
    // byte-comparing the binaries would clobber the newer build with the
    // stale release asset. The commit is the monotonic signal the version
    // string cannot carry. Release assets are built in CI from a git
    // checkout, so the SHA is always present there; a non-git build (e.g.
    // `cargo install` from a crates.io tarball) falls back to a sentinel
    // that the updater treats as "cannot verify, keep what is installed".
    let commit = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|sha| sha.trim().to_owned())
        .filter(|sha| !sha.is_empty())
        .unwrap_or_else(|| "unknown".to_owned());
    println!("cargo:rustc-env=PRELOOP_BUILD_COMMIT={commit}");
    let mut ref_paths = vec![String::from("../../.git/HEAD")];
    if let Ok(output) = Command::new("git")
        .args(["rev-parse", "--symbolic-full-name", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
    {
        if output.status.success() {
            if let Ok(ref_name) = String::from_utf8(output.stdout) {
                let ref_name = ref_name.trim();
                if let Some(short) = ref_name.strip_prefix("refs/") {
                    ref_paths.push(format!("../../.git/{short}"));
                }
            }
        }
    }
    ref_paths.push(String::from("../../.git/packed-refs"));
    for path in ref_paths {
        println!("cargo:rerun-if-changed={path}");
    }
}
