//! Generates version-pin constants from `versions.toml` for the runner,
//! so Node externals versions are never hardcoded separately.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let versions_path = manifest_dir.join("../../versions.toml");
    let text = fs::read_to_string(&versions_path).expect("versions.toml must exist");

    let mut pins: BTreeMap<String, String> = BTreeMap::new();
    let mut sha_pins: BTreeMap<String, String> = BTreeMap::new();
    let mut in_sha_section = false;

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            let section = line[1..line.len() - 1].trim().to_ascii_lowercase();
            in_sha_section = section == "node_externals.sha256";
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().to_owned();
        let value = value.trim();
        if !(value.starts_with('"') && value.ends_with('"')) {
            continue;
        }
        let value = value[1..value.len() - 1].to_owned();
        pins.insert(key.clone(), value.clone());
        if in_sha_section {
            sha_pins.insert(key.clone(), value.clone());
        }
    }

    let mut out = String::from("// Generated by build.rs from versions.toml. Do not edit.\n");

    for (key, value) in &pins {
        let const_name = key.trim().to_uppercase().replace(['.', '-'], "_");
        out.push_str(&format!("pub const {const_name}: &str = \"{value}\";\n"));
    }

    let node20 = pins
        .get("node20_externals_version")
        .or_else(|| pins.get("node20_version"))
        .cloned()
        .unwrap_or_else(|| "20.19.0".to_owned());
    let node24 = pins
        .get("node24_externals_version")
        .or_else(|| pins.get("node24_version"))
        .cloned()
        .unwrap_or_else(|| "24.3.0".to_owned());

    if !pins.contains_key("node20_externals_version") && !pins.contains_key("node20_version") {
        out.push_str(&format!(
            "pub const NODE20_EXTERNALS_VERSION: &str = \"{node20}\";\n"
        ));
    }
    if pins.contains_key("node20_version") && !pins.contains_key("node20_externals_version") {
        out.push_str(&format!(
            "pub const NODE20_EXTERNALS_VERSION: &str = \"{node20}\";\n"
        ));
    }
    if !pins.contains_key("node24_externals_version") && !pins.contains_key("node24_version") {
        out.push_str(&format!(
            "pub const NODE24_EXTERNALS_VERSION: &str = \"{node24}\";\n"
        ));
    }
    if pins.contains_key("node24_version") && !pins.contains_key("node24_externals_version") {
        out.push_str(&format!(
            "pub const NODE24_EXTERNALS_VERSION: &str = \"{node24}\";\n"
        ));
    }

    out.push_str("pub const NODE_EXTERNALS_SHA256: &[(&str, &str)] = &[\n");
    for (key, value) in &sha_pins {
        let ek = key.replace('\\', "\\\\").replace('"', "\\\"");
        let ev = value.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!("    (\"{ek}\", \"{ev}\"),\n"));
    }
    out.push_str("];\n");
    out.push_str("pub fn node_externals_pinned_sha256(key: &str) -> Option<&'static str> {\n");
    out.push_str(
        "    NODE_EXTERNALS_SHA256.iter().find_map(|(k, v)| if *k == key { Some(*v) } else { None })\n",
    );
    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("pins.rs"), out).expect("write pins.rs");
    println!("cargo:rerun-if-changed=../../versions.toml");
}
