name: concurrency-14-jobset-embedded-only
on: workflow_dispatch
jobs:
  caller-job:
    uses: ./.github/workflows/reusable-callee.yml
    with:
      val: "embedded-only"
      concurrency_group: "embedded-only-group"
